eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: http://localhost:4200,http://localhost:80
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: game-service
          uri: lb://game-service
          predicates:
            - Path=/game/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
