eureka:
  instance:
    hostname: gateway-service.d7esfnaghvbthzax.polandcentral.azurecontainer.io
  client:
    serviceUrl:
      defaultZone: http://registry-service.dvchg3d0g2htg5bw.polandcentral.azurecontainer.io:8761/eureka/
spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: http://86.121.160.225:4200,http://86.121.160.225,http://rentals-app.caafbsdkdvc8ebc7.germanywestcentral.azurecontainer.io
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: game-service
          uri: lb://game-service
          predicates:
            - Path=/game/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
